version: '3'
services:
  front-end:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Map port 3000 in the container to port 3000 on the host
    environment:
      - NODE_ENV=production
    # volumes:
    #   - .:/app  # Optional: If you want to mount the current directory, for development purposes
    # command: npm start  # Run the Next.js app in production mode
  stt:
    build:
      context: ./stt 
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
  
  tts:
    build:
      context: ./tts
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - PORT=8001